# Generated by Django 5.0.2 on 2024-02-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='slug',
        ),
    ]
