# Generated by Django 5.0.1 on 2024-03-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name': 'Типы предметов', 'verbose_name_plural': 'Типы предметов'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Места нахождения', 'verbose_name_plural': 'Места нахождения'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id'], 'verbose_name': 'Роли', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='usermark',
            options={'ordering': ['item_card'], 'verbose_name': 'Отметки пользователей', 'verbose_name_plural': 'Отметки пользователей'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='class',
            name='rus_name',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemcard', verbose_name='Карточка предмета'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='item_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class', verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='place_found',
            field=models.CharField(max_length=255, null=True, verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='resp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='time_found',
            field=models.DateTimeField(null=True, verbose_name='Время нахождения'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='item_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemcard', verbose_name='Карточка предмета'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
