# Generated by Django 5.0.2 on 2024-02-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_class_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='itemcard',
            name='place_found',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcard',
            name='time_found',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
