# Generated by Django 5.0.1 on 2024-02-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_class_comment_item_itemcard_role_usermark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcard',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='itemcard',
            name='item',
        ),
        migrations.AddField(
            model_name='itemcard',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.comment'),
        ),
        migrations.AddField(
            model_name='itemcard',
            name='item_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class'),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='resp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='item_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemcard'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
