# Generated by Django 5.0.1 on 2024-02-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_itemcard_comment_id_remove_itemcard_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcard',
            options={'ordering': ['time_create'], 'verbose_name': 'Карточки предметов', 'verbose_name_plural': 'Карточки предметов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
