# Generated by Django 5.0.2 on 2024-02-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcard',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='item_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemcard'),
        ),
    ]
