# Generated by Django 5.0.2 on 2024-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_itemcard_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='rus_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcard',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
