# Generated by Django 5.0.2 on 2024-02-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcard',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.comment'),
        ),
    ]
